name: app_ascs
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.6
  google_sign_in: ^7.2.0
  http_parser: ^4.0.2
  path_provider: ^2.1.1
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  amplify_flutter: ^2.6.1
  amplify_storage_s3: ^2.6.1
  amplify_core: ^2.6.1
  amplify_auth_cognito: ^2.6.1
  amplify_api: ^2.6.1
  connectivity_plus: ^7.0.0

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Functional Programming
  dartz: ^0.10.1

  # Dependency Injection
  get_it: ^9.0.5

  bloc: ^9.1.0

  # Para procesar PDFs
  syncfusion_flutter_pdf: ^31.2.12 # Última versión al 18 de noviembre de 2025

  # Para descargar archivos
  http: ^1.1.0

  # Para descomprimir ZIP
  archive: ^4.0.7

  # Para manejo de rutas
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.0.0
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imagenes/foco_auscultacion.jpg
    - assets/config/medical_config.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/Corazon.png"
  adaptive_icon_background: "#84A0E3"
  adaptive_icon_foreground: "assets/icons/Corazon.png"
